name: eso
description: 亦搜，亦看，亦闻

version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git
  cupertino_icons: ^0.1.2
  path_provider: ^1.2.0
  provider: ^3.1.0+1
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  chewie: ^0.9.7
  equatable: ^0.6.1
#  flutter_liquidcore: ^0.6.0+1
#  flutter_liquidcore: ^1.0.0
  floor: ^0.8.0
  url_launcher: ^5.1.2
  fast_gbk: ^0.1.1+1
  flutter_bloc: ^1.0.0
  flutter_share: ^1.0.2+1
  crypto: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.8.0
  build_runner: ^1.6.7

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
